name: 🚀 Deploy NestJS Blog Backend API to VPS

on:
  push:
    branches: [main, feature/users-entities]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy project to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.VPS_KEY }}
        source: "."
        target: "/home/banosc/banos-entrevistas-junior"

    - name: Run deploy commands on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.VPS_KEY }}
        script: |
          set -e
          cd /home/banosc/banos-entrevistas-junior/simulador_entrevistas

          sudo lsof -t -i:3000 | xargs -r sudo kill -9 || true

          printf "%s" "${{ secrets.ENV_FILE }}" > .env

          npm install
          npm run build

          pm2 stop banos-entrevistas-junior-api || true
          pm2 delete banos-entrevistas-junior-api || true
          pm2 start dist/main.js --name banos-entrevistas-junior-api
          pm2 save